package be.howest.twentytwo.parametergame.model.messaging;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 * Manages all game events that are generated by systems to be distributed to any relevant
 * observers.
 */
public class MessageQueue implements Iterable<IEventMessage>{
	
	private final List<IEventMessage> messages;
	
	public MessageQueue(){
		this.messages = new ArrayList<IEventMessage>();
	}
	
	public void addMessage(IEventMessage message){
		messages.add(message);
	}

	public void clearMessages(){
		messages.clear();
	}
	
	@Override
	public Iterator<IEventMessage> iterator() {
		return messages.iterator();
	}
	
}
