package be.howest.twentytwo.parametergame.model.event;

public enum EventEnum {
	PLAYER_HIT, PLAYER_PICKUP, PLAYER_KILLED, ENEMY_SPAWNED, ENEMY_KILLED, ENEMY_HIT, WEAPON_FIRED, PLANET_CRASH, GAME_START, GAME_END, DESTROY_ENTITY, GAME_SPAWN_DEPLETED;
}